[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/',
 '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
 '@NFT-Contract/=lib/NFT-Contract/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
